# Generated by Django 4.1 on 2022-08-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Nombre"
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Apellido")),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="País de origen",
                        max_length=50,
                        null=True,
                        verbose_name="Nacionalidad",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Autores",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        help_text="Ingresa un género de libro (ej. Ciencia Ficción, Misterio)",
                        max_length=100,
                        verbose_name="Género",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Título")),
                (
                    "editorial",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Editorial"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="ISBN"
                    ),
                ),
                ("price", models.FloatField(verbose_name="Precio")),
                (
                    "resumen",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Reseña"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="libreria.author",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(to="libreria.genre", verbose_name="Género"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="libreria.language",
                    ),
                ),
            ],
            options={
                "ordering": ["title", "editorial"],
            },
        ),
    ]
