# Generated by Django 4.1 on 2022-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0002_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="libreria.genre", verbose_name="Género"),
        ),
    ]
