# Generated by Django 4.1 on 2022-09-01 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0004_book_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["genre"],
                "verbose_name": "Género",
                "verbose_name_plural": "Géneros",
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author_books",
                to="libreria.author",
                verbose_name="Autor",
            ),
        ),
    ]
